export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA'
export const REMOVE_TAREFA = 'REMOVE_TAREFA'

export const NOTIFICAR = 'NOTIFICAR'